name: Build and publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and publish using gradle
        env:
          bintray_user: ${{secrets.bintray_user}}
          bintray_key: ${{secrets.bintray_key}}
        run: ./gradlew bintrayUpload